### ISSUE TITLE
View complete battlefield

### ISSUE THREAD

**Issue by pranoyk** [STEP-tw/stratego-gamblers#13]
As a Player

I want to view the whole battlefield

So that I will make my move.

**Additional Details**

Assumptions : 
- Both the players have deployed the whole army and are ready 

Dependencies : 
- Both the players should set their homeland
- Both the players should be ready for battle

**Acceptance Criteria**

- [x] Criteria 1
  - Given I am on setup page and have deployed my whole army on my homeland
  - When I click on Ready
  - Then I will see the whole battlefield

- [x] Criteria 2
  - Given I am on setup page and have deployed my whole army on my homeland
  - When I click on Ready
  - Then I will see the whole battlefield and my army on it so that I will make my move

- [x] Criteria 3
  - Given I've deployed my army and I clicked ready
  - When I'm seeing the army
  - Then my army is below rows of battlefield and opponent army is in above rows of the battlefield.

- [x] Criteria 4
  - Given I am on setup page and have deployed my whole army on my homeland
  - When I click on Ready
  - Then I will see the whole battlefield and opponent army’s location

- [x] Criteria 5
  - Given I've clicked ready button after placing my army I reached playing game page
  - When I'm watching battlefield
  - Then I should be able to understand lake area.

**QA Criteria**
 - [x] Should not allow to view battlefield by hitting url
 - [x] Should view opponent's armies location but don't view their faces
 - [x] Should not view battlefield until both players are ready
 - [x] The army position should be same as that have been set up in setup phase

**Comment by sayima** [comment]
Player is now been redirected from setup phase to playing phase when both the players are ready
