### ISSUE TITLE
Update Battlefield

### ISSUE THREAD

**Issue by pranoyk** [STEP-tw/stratego-gamblers#15]
As a player

I want to see my moves made and my opponents moves made

So that I can continue my strategy

**Additional Details**

Assumptions : 
- Both the players have joined the game

Dependencies : 
- View battlefield story should be done
- Players have the ability to move the playing piece
- Split screen should be done

**Acceptance Criteria**

- [x] Criteria 1
  - Given the game has started
  - When I make a move of my playing piece
  - Then my playing piece moves to that location
- [x] Criteria 2
  - Given the game has started
  - When my opponents make a move of his playing piece
  - Then my opponents playing piece moves to that location

**Comment by ravinderj** [comment]
Improving data structure to send to client side

**Comment by ravinderj** [comment]
Improving data structure to send to client side
